# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 427af550cab175fd34f5f1729bc1b548896ea693ddc02c9d59819b1438a562185fbacb2148794b862a21e5e37f990548e6baff711c646ba2e0c505187594e3ed

test:
  secret_key_base: 194af060095517b1819d5b1c7997775756f085e988b053ab1b6b7d81ad7b17d24cff6226d3233e7dc0b9b13793ecd8f254ac4b6202e5516cae75b25b99fb697d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
